# Generated by Django 3.2.5 on 2021-08-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('photo1', models.ImageField(blank=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, upload_to='')),
                ('photo4', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('info_1', models.CharField(max_length=30)),
                ('info_2', models.CharField(max_length=30)),
                ('info_3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Otb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='')),
                ('name1', models.CharField(max_length=20)),
                ('photo2', models.ImageField(blank=True, upload_to='')),
                ('name2', models.CharField(max_length=20)),
                ('photo3', models.ImageField(blank=True, upload_to='')),
                ('name3', models.CharField(max_length=20)),
                ('photo4', models.ImageField(blank=True, upload_to='')),
                ('name4', models.CharField(max_length=20)),
                ('photo5', models.ImageField(blank=True, upload_to='')),
                ('name5', models.CharField(max_length=20)),
                ('photo6', models.ImageField(blank=True, upload_to='')),
                ('name6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
