# Generated by Django 3.2.5 on 2021-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_qna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='image1',
            field=models.ImageField(blank=True, upload_to='shop/media'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='image2',
            field=models.ImageField(blank=True, upload_to='shop/media'),
        ),
    ]
