# Generated by Django 3.2.5 on 2021-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210819_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='image2',
        ),
        migrations.AddField(
            model_name='qna',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
