# Generated by Django 3.2.5 on 2021-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210819_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
